name: Deribit Data Collection

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (GitHub's minimum reliable interval)
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Set up Google Cloud credentials
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > login.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=login.json" >> $GITHUB_ENV
      
      - name: Run data collection script
        run: python flow.py
